#include "web_ui.h"

const char web_ui_html[] =
    "<!doctype html><html lang=en><head><meta charset=utf-8>"
    "<meta name=viewport content='width=device-width,initial-scale=1'>"
    "<title>PicoW Keyboard</title><style>"
    ":root{color-scheme:light dark;font-family:system-ui,sans-serif;background:#f3f5f7;color:#17202a}"
    "*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0;padding:20px}main{max-width:720px;margin:auto}"
    "h1{font-size:1.45rem;margin:0 0 4px}.sub{color:#65717d;margin:0 0 20px}"
    ".card{background:#fff;border:1px solid #dce1e5;border-radius:12px;padding:16px;margin:12px 0;box-shadow:0 2px 8px #0000000b}"
    ".row{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}"
    ".state{font-weight:700}.muted{color:#65717d;font-size:.9rem}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}"
    "button{border:0;border-radius:8px;padding:10px 14px;font:inherit;font-weight:650;background:#e8edf2;color:#17202a;cursor:pointer}"
    "button.primary{background:#1769e0;color:#fff}button.danger{background:#fff0f0;color:#a32121}button:disabled{opacity:.5;cursor:wait}"
    "ul{list-style:none;margin:12px 0 0;padding:0}.device{padding:13px 0;border-top:1px solid #e5e9ec}"
    ".device:first-child{border-top:0}.name{font-weight:650}.badges{display:flex;gap:5px;flex-wrap:wrap;margin-top:5px}"
    ".badge{font-size:.72rem;background:#e8edf2;border-radius:999px;padding:2px 7px}.badge.on{background:#daf5e5;color:#17633a}"
    "#message{min-height:24px;margin:10px 2px;color:#17633a}#message.error{color:#a32121}"
    "@media(prefers-color-scheme:dark){:root{background:#11161b;color:#edf2f6}.card{background:#1b2229;border-color:#303941}.muted,.sub{color:#aab4bd}button{background:#34404a;color:#fff}button.danger{background:#402528;color:#ffb7b7}.device{border-color:#303941}.badge{background:#34404a}.badge.on{background:#194b32;color:#a9edc6}}"
    "</style></head><body><main><h1>PicoW Keyboard</h1>"
    "<p class=sub>Bluetooth keyboard connection settings</p>"
    "<section id=pairing class=card hidden><div class=muted>Pairing PIN</div>"
    "<div id=pin class=state></div><p>Type this PIN on the Bluetooth keyboard, then press Enter.</p></section>"
    "<section class=card><div class=row><div><div class=muted>Connection status</div>"
    "<div id=state class=state>Loading...</div></div><button id=refresh>Refresh</button></div>"
    "<div id=selected class=muted></div><div class=actions>"
    "<button id=reconnect class=primary>Reconnect</button><button id=disconnect>Disconnect</button>"
    "<button id=forget class=danger>Forget pairing</button></div></section>"
    "<section class=card><div class=row><div><div class=state>Nearby devices</div>"
    "<div class=muted>Choose a keyboard after scanning.</div></div><button id=scan class=primary>Scan</button></div>"
    "<ul id=devices><li class=muted>No scan results.</li></ul></section>"
    "<div id=message role=status aria-live=polite></div><div id=version class=muted></div></main><script>"
    "const $=id=>document.getElementById(id);"
    "let busy=false,currentState='Unknown';function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}"
    "function updateControls(){$('refresh').disabled=busy;$('scan').disabled=busy||currentState!=='Idle';"
    "$('forget').disabled=busy||!['Idle','HIDConnected','Disconnected'].includes(currentState);"
    "$('reconnect').disabled=busy||currentState!=='Idle';const active=['Connecting','Connected','Authenticating','ServiceDiscovery','OpeningControl','SettingBootProtocol','OpeningInterrupt','HIDConnected'];"
    "$('disconnect').disabled=busy||!active.includes(currentState);"
    "document.querySelectorAll('[data-connect]').forEach(button=>button.disabled=busy||currentState!=='Idle'||button.dataset.connect!=='yes')}"
    "function lock(value){busy=value;updateControls()}"
    "async function api(path,method='GET'){const response=await fetch(path,{method,cache:'no-store'});"
    "const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data}"
    "function badge(text,on=false){const span=document.createElement('span');span.className='badge'+(on?' on':'');span.textContent=text;return span}"
    "function render(data){currentState=data.state||'Unknown';$('state').textContent=currentState;$('version').textContent='Firmware '+(data.version||'unknown');"
    "$('pairing').hidden=!data.pairingPin;$('pin').textContent=data.pairingPin||'';"
    "$('selected').textContent=data.selectedDevice?'Selected: '+data.selectedDevice:'No saved keyboard';"
    "const list=$('devices');list.replaceChildren();const devices=data.devices||[];"
    "if(!devices.length){const empty=document.createElement('li');empty.className='muted';empty.textContent='No devices found.';list.append(empty);updateControls();return}"
    "devices.forEach(device=>{const item=document.createElement('li');item.className='device';"
    "const row=document.createElement('div');row.className='row';const info=document.createElement('div');"
    "const name=document.createElement('div');name.className='name';name.textContent=device.name||'Unknown device';"
    "const address=document.createElement('div');address.className='muted';address.textContent=device.address+(device.hasRssi?'  '+device.rssi+' dBm':'');"
    "const badges=document.createElement('div');badges.className='badges';if(device.keyboard)badges.append(badge('Keyboard'));"
    "if(device.reportNkro)badges.append(badge('NKRO'));if(device.reportConsumerControl)badges.append(badge('Media keys'));"
    "if(device.reportIds)badges.append(badge('Report IDs'));if(device.reportDescriptorTooLarge)badges.append(badge('Descriptor too large'));"
    "else if(device.reportDescriptorPresent&&!device.reportDescriptorValid)badges.append(badge('Invalid descriptor'));"
    "if(device.bonded)badges.append(badge('Paired'));if(device.connected)badges.append(badge('Connected',true));"
    "info.append(name,address,badges);row.append(info);if(device.keyboard){const connect=document.createElement('button');"
    "connect.textContent=device.connected?'Connected':'Connect';connect.className=device.connected?'':'primary';"
    "connect.dataset.connect=device.connected?'no':'yes';connect.onclick=()=>action('/api/connect?address='+device.address,'Connecting...');row.append(connect)}"
    "item.append(row);list.append(item)});updateControls()}"
    "async function refresh(quiet=false){try{render(await api('/api/status'));if(!quiet)message('Status updated.')}catch(error){message(error.message,true)}}"
    "async function action(path,text){lock(true);message(text);try{await api(path,'POST');await new Promise(resolve=>setTimeout(resolve,700));await refresh(true);message('Command accepted.')}catch(error){message(error.message,true)}finally{lock(false)}}"
    "$('refresh').onclick=()=>refresh();$('scan').onclick=()=>action('/api/scan','Scanning...');"
    "$('reconnect').onclick=()=>action('/api/reconnect','Reconnecting...');$('disconnect').onclick=()=>action('/api/disconnect','Disconnecting...');"
    "$('forget').onclick=()=>{if(confirm('Forget the saved pairing information?'))action('/api/forget','Removing pairing...')};"
    "updateControls();refresh(true);setInterval(()=>{if(!busy)refresh(true)},3000);</script></body></html>";

const size_t web_ui_html_length = sizeof(web_ui_html) - 1;
